# yaml-language-server: $schema=https://json-schema.axonivy.com/14.0-dev/config/databases.json
Databases:
  SystemDatabase:
    Url: jdbc:hsqldb:mem:AxonIvySystemDatabase
    Driver: org.hsqldb.jdbcDriver
