FROM axonivy/axonivy-engine:sprint

ADD --chown=ivy:ivy testProjects/7.2.0/Performance/target/performance-1.0.0-SNAPSHOT.iar /usr/lib/axonivy-engine/deploy/performance.iar

ADD --chown=ivy:ivy docker/ivy/app-performance.yaml /usr/lib/axonivy-engine/configuration/performance/app.yaml
