package performance.client;

import javax.annotation.Generated;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2020-06-09T08:48:51.807+02:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://performance/", name = "PersonService")
@XmlSeeAlso({ObjectFactory.class, process.webservice.ivy.ivyteam.ch.client.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2020-06-09T08:48:51.807+02:00", comments = "Apache CXF 3.2.6")
public interface PersonService {

    @WebMethod
    @WebResult(name = "callResponse", targetNamespace = "http://performance/", partName = "parameters")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2020-06-09T08:48:51.807+02:00")
    public CallResponse call(
        @WebParam(partName = "parameters", name = "call", targetNamespace = "http://performance/")
        Call parameters
    ) throws WebServiceProcessTechnicalException;
}
